"""HS2 chapter names used in the sector table (moved from TRI-sector.ipynb)."""

HS2_NAMES = {
    '01': 'Live Animals',
    '02': 'Meat',
    '03': 'Fish',
    '04': 'Dairy Products',
    '05': 'Animal Products',
    '06': 'Live Plants',
    '07': 'Vegetables',
    '08': 'Fruit \\& Nuts',
    '09': 'Coffee, Tea \\& Spices',
    '10': 'Cereals',
    '11': 'Milling Products',
    '12': 'Oil Seeds',
    '13': 'Vegetable Extracts',
    '14': 'Vegetable Plaiting Materials',
    '15': 'Animal/Vegetable Fats',
    '16': 'Prepared Meat/Fish',
    '17': 'Sugars',
    '18': 'Cocoa Products',
    '19': 'Prepared Cereals',
    '20': 'Prepared Vegetables/Fruit',
    '21': 'Miscellaneous Food',
    '22': 'Beverages \\& Vinegar',
    '23': 'Food Industry Waste',
    '24': 'Tobacco',
    '25': 'Salt, Sulfur \\& Minerals',
    '26': 'Ores',
    '27': 'Mineral Fuels \\& Oils',
    '28': 'Inorganic Chemicals',
    '29': 'Organic Chemicals',
    '30': 'Pharmaceuticals',
    '31': 'Fertilizers',
    '32': 'Dyes \\& Paints',
    '33': 'Perfumes \\& Cosmetics',
    '34': 'Soap \\& Cleaning Products',
    '35': 'Protein Substances',
    '36': 'Explosives',
    '37': 'Photographic Goods',
    '38': 'Miscellaneous Chemicals',
    '39': 'Plastics',
    '40': 'Rubber',
    '41': 'Raw Hides \\& Skins',
    '42': 'Leather Articles',
    '43': 'Furskins',
    '44': 'Wood',
    '45': 'Cork',
    '46': 'Straw Articles',
    '47': 'Pulp',
    '48': 'Paper \\& Paperboard',
    '49': 'Printed Books',
    '50': 'Silk',
    '51': 'Wool',
    '52': 'Cotton',
    '53': 'Vegetable Textile Fibers',
    '54': 'Man-Made Filaments',
    '55': 'Man-Made Staple Fibers',
    '56': 'Wadding \\& Felt',
    '57': 'Carpets',
    '58': 'Special Woven Fabrics',
    '59': 'Impregnated Textiles',
    '60': 'Knitted Fabrics',
    '61': 'Knitted Apparel',
    '62': 'Woven Apparel',
    '63': 'Textile Articles',
    '64': 'Footwear',
    '65': 'Headgear',
    '66': 'Umbrellas',
    '67': 'Prepared Feathers',
    '68': 'Stone Articles',
    '69': 'Ceramic Products',
    '70': 'Glass',
    '71': 'Precious Stones \\& Metals',
    '72': 'Iron \\& Steel',
    '73': 'Iron/Steel Articles',
    '74': 'Copper',
    '75': 'Nickel',
    '76': 'Aluminum',
    '78': 'Lead',
    '79': 'Zinc',
    '80': 'Tin',
    '81': 'Other Base Metals',
    '82': 'Tools',
    '83': 'Metal Articles',
    '84': 'Machinery',
    '85': 'Electrical Equipment',
    '86': 'Railway Equipment',
    '87': 'Vehicles',
    '88': 'Aircraft',
    '89': 'Ships \\& Boats',
    '90': 'Optical/Medical Equipment',
    '91': 'Clocks \\& Watches',
    '92': 'Musical Instruments',
    '93': 'Arms \\& Ammunition',
    '94': 'Furniture',
    '95': 'Toys \\& Games',
    '96': 'Miscellaneous Manufactured Articles',
    '97': 'Art \\& Antiques',
    '98': 'Special Classification',
    '99': 'Special Classification',
}
